/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Articulos;
import modelo.Libros;
import modelo.Notas_articulo;
import modelo.Notas_libro;

/**
 *
 * @author ciuda
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        añadir_libro = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtañadlibrotitulo = new javax.swing.JTextField();
        txtaañadlibroautor = new javax.swing.JTextField();
        txtañadlibronpag = new javax.swing.JTextField();
        txtañadlibroedit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnañadirlibro = new javax.swing.JButton();
        txtañadlibroaño = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        añadir_articulo = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtañadartautor = new javax.swing.JTextField();
        txtañadarttitulo = new javax.swing.JTextField();
        txtañadartnomrevist = new javax.swing.JTextField();
        txtañadartaño = new javax.swing.JTextField();
        txtañadartmes = new javax.swing.JTextField();
        txtañadartpaginic = new javax.swing.JTextField();
        txtañadartpagfin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnañadirarticulo = new javax.swing.JButton();
        modificar_libro = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtmodiflibrotitulo = new javax.swing.JTextField();
        txtmodiflibroautor = new javax.swing.JTextField();
        txtmodiflibronpag = new javax.swing.JTextField();
        txtmodiflibroedit = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnmodiflibro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtmodiflibroaño = new javax.swing.JTextField();
        modificar_articulo = new javax.swing.JDialog();
        txtmodifartpaginic = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtmodifartpagfin = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtmodifartautor = new javax.swing.JTextField();
        txtmodifarttitulo = new javax.swing.JTextField();
        txtmodifartnomrevist = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtmodifartaño = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtmodifartmes = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnmodifarticulo = new javax.swing.JButton();
        añadirnotalibro = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtañadnotlibtema = new javax.swing.JTextField();
        txtañadnotlibtit = new javax.swing.JTextField();
        txtañadnotlibtexto = new javax.swing.JTextField();
        btnañadnotalibro = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        añadirnotaarticulo = new javax.swing.JDialog();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtañadnotarttema = new javax.swing.JTextField();
        txtañadnotarttitulo = new javax.swing.JTextField();
        txtañadnotarttexto = new javax.swing.JTextField();
        btnañadnotaarticulo = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        modificarnota_libro = new javax.swing.JDialog();
        txtmodifnotlibtitulo = new javax.swing.JTextField();
        txtmodifnotlibtema = new javax.swing.JTextField();
        txtmodifnotlibtexto = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        btnmodifnotlibro = new javax.swing.JButton();
        modificarnota_articulo = new javax.swing.JDialog();
        txtmodifnotarttitulo = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtmodifnotarttexto = new javax.swing.JTextField();
        txtmodifnotarttema = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        btnmodifnotarticulo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelibro = new javax.swing.JPanel();
        scrolllibro = new javax.swing.JScrollPane();
        tablalibro = new javax.swing.JTable();
        añadirlibro = new javax.swing.JButton();
        modiflibro = new javax.swing.JButton();
        notalibro = new javax.swing.JButton();
        fiellibbusc = new javax.swing.JTextField();
        lablibbusc = new javax.swing.JLabel();
        buscarlibro = new javax.swing.JButton();
        ComboBoxlibros = new javax.swing.JComboBox<>();
        btnelimlibro = new javax.swing.JButton();
        txtinvisibleelimlibro = new javax.swing.JTextField();
        panelartic = new javax.swing.JPanel();
        scrollartic = new javax.swing.JScrollPane();
        tablartic = new javax.swing.JTable();
        añadirartic = new javax.swing.JButton();
        modifartic = new javax.swing.JButton();
        notaartic = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fielartbusc = new javax.swing.JTextField();
        buscararticulo = new javax.swing.JButton();
        ComboBoxarticulo = new javax.swing.JComboBox<>();
        btnelimarticulo = new javax.swing.JButton();
        txtinvisibleelimart = new javax.swing.JTextField();
        pabelnotas = new javax.swing.JPanel();
        scrollnotas = new javax.swing.JScrollPane();
        tablanotaslibro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbuscnottit = new javax.swing.JTextField();
        txtbuscnottem = new javax.swing.JTextField();
        buscnotatit = new javax.swing.JButton();
        buscnotatem = new javax.swing.JButton();
        scrollnotas1 = new javax.swing.JScrollPane();
        tablanotasarticulo = new javax.swing.JTable();
        ComboBox1 = new javax.swing.JComboBox<>();
        ComboBox2 = new javax.swing.JComboBox<>();
        btnmodifnotlib = new javax.swing.JButton();
        btnmodifnotart = new javax.swing.JButton();

        jLabel5.setText("Titulo:");

        jLabel6.setText("Autor:");

        jLabel7.setText("Nª Paginas:");

        jLabel8.setText("Editorial:");

        txtañadlibrotitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañadlibrotituloActionPerformed(evt);
            }
        });

        txtaañadlibroautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaañadlibroautorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 24)); // NOI18N
        jLabel9.setText("Añadir Libro");

        btnañadirlibro.setText("Añadir");

        jLabel4.setText("Año");

        javax.swing.GroupLayout añadir_libroLayout = new javax.swing.GroupLayout(añadir_libro.getContentPane());
        añadir_libro.getContentPane().setLayout(añadir_libroLayout);
        añadir_libroLayout.setHorizontalGroup(
            añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadir_libroLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadir_libroLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addGroup(añadir_libroLayout.createSequentialGroup()
                        .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtañadlibrotitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(txtaañadlibroautor)
                        .addComponent(txtañadlibronpag)
                        .addComponent(txtañadlibroedit))
                    .addComponent(txtañadlibroaño, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnañadirlibro)
                .addGap(22, 22, 22))
        );
        añadir_libroLayout.setVerticalGroup(
            añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadir_libroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addGap(43, 43, 43)
                .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtañadlibrotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtaañadlibroautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtañadlibronpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtañadlibroedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(añadir_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnañadirlibro)
                    .addComponent(txtañadlibroaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jLabel11.setText("Autor:");

        jLabel12.setText("Titulo:");

        jLabel13.setText("Nombre revista:");

        jLabel14.setText("Año:");

        jLabel15.setText("Mes:");

        jLabel16.setText("Pag. inicio:");

        jLabel17.setText("Pag. fin:");

        txtañadartautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañadartautorActionPerformed(evt);
            }
        });

        txtañadartnomrevist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañadartnomrevistActionPerformed(evt);
            }
        });

        txtañadartmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañadartmesActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 24)); // NOI18N
        jLabel18.setText("Añadir Articulo");

        btnañadirarticulo.setText("Añadir");

        javax.swing.GroupLayout añadir_articuloLayout = new javax.swing.GroupLayout(añadir_articulo.getContentPane());
        añadir_articulo.getContentPane().setLayout(añadir_articuloLayout);
        añadir_articuloLayout.setHorizontalGroup(
            añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadir_articuloLayout.createSequentialGroup()
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(añadir_articuloLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(añadir_articuloLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(50, 50, 50)
                                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtañadartautor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtañadarttitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtañadartnomrevist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(txtañadartaño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(txtañadartmes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(txtañadartpaginic, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtañadartpagfin, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(añadir_articuloLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btnañadirarticulo))))
                    .addGroup(añadir_articuloLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel18)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        añadir_articuloLayout.setVerticalGroup(
            añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadir_articuloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtañadartautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtañadarttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtañadartnomrevist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtañadartaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtañadartmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtañadartpaginic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(añadir_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtañadartpagfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnañadirarticulo)
                .addContainerGap())
        );

        jLabel20.setText("Titulo:");

        jLabel21.setText("Autor:");

        jLabel22.setText("Nª Paginas:");

        jLabel23.setText("Editorial:");

        txtmodiflibrotitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodiflibrotituloActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jLabel24.setText("Modificar Libro:");

        btnmodiflibro.setText("Modificar");
        btnmodiflibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodiflibroActionPerformed(evt);
            }
        });

        jLabel10.setText("Año:");

        javax.swing.GroupLayout modificar_libroLayout = new javax.swing.GroupLayout(modificar_libro.getContentPane());
        modificar_libro.getContentPane().setLayout(modificar_libroLayout);
        modificar_libroLayout.setHorizontalGroup(
            modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_libroLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificar_libroLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificar_libroLayout.createSequentialGroup()
                        .addComponent(btnmodiflibro)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificar_libroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(91, 91, 91)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmodiflibroautor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtmodiflibrotitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmodiflibroedit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmodiflibronpag)
                    .addComponent(txtmodiflibroaño))
                .addGap(97, 97, 97))
        );
        modificar_libroLayout.setVerticalGroup(
            modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificar_libroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtmodiflibrotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtmodiflibroautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtmodiflibronpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtmodiflibroedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(modificar_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmodiflibroaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnmodiflibro)
                .addContainerGap())
        );

        txtmodifartpaginic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodifartpaginicActionPerformed(evt);
            }
        });

        jLabel25.setText("Año:");

        jLabel26.setText("Mes:");

        jLabel27.setText("Pag. inicio:");

        jLabel28.setText("Pag. fin:");

        txtmodifartautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodifartautorActionPerformed(evt);
            }
        });

        jLabel30.setText("Autor:");

        txtmodifartaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodifartañoActionPerformed(evt);
            }
        });

        jLabel31.setText("Titulo:");

        jLabel32.setText("Nombre revista:");

        jLabel33.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jLabel33.setText("Modificar Articulo:");

        btnmodifarticulo.setText("Modificar");

        javax.swing.GroupLayout modificar_articuloLayout = new javax.swing.GroupLayout(modificar_articulo.getContentPane());
        modificar_articulo.getContentPane().setLayout(modificar_articuloLayout);
        modificar_articuloLayout.setHorizontalGroup(
            modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_articuloLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel31)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30)
                    .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificar_articuloLayout.createSequentialGroup()
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmodifartnomrevist)
                            .addComponent(txtmodifartaño, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmodifartmes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(modificar_articuloLayout.createSequentialGroup()
                                .addComponent(txtmodifartpagfin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtmodifartautor)
                            .addComponent(txtmodifarttitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnmodifarticulo))
                    .addGroup(modificar_articuloLayout.createSequentialGroup()
                        .addComponent(txtmodifartpaginic, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificar_articuloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(125, 125, 125))
        );
        modificar_articuloLayout.setVerticalGroup(
            modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_articuloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificar_articuloLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(25, 25, 25)
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtmodifartautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtmodifarttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtmodifartnomrevist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmodifartaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtmodifartmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtmodifartpaginic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(modificar_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtmodifartpagfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificar_articuloLayout.createSequentialGroup()
                        .addComponent(btnmodifarticulo)
                        .addContainerGap())))
        );

        jLabel34.setText("Tema:");

        jLabel35.setText("Titulo de referencia:");

        jLabel36.setText("Texto:");

        txtañadnotlibtema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañadnotlibtemaActionPerformed(evt);
            }
        });

        btnañadnotalibro.setText("Añadir");

        jLabel37.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jLabel37.setText("Añadir Nota:");

        javax.swing.GroupLayout añadirnotalibroLayout = new javax.swing.GroupLayout(añadirnotalibro.getContentPane());
        añadirnotalibro.getContentPane().setLayout(añadirnotalibroLayout);
        añadirnotalibroLayout.setHorizontalGroup(
            añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirnotalibroLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36))
                .addGap(37, 37, 37)
                .addGroup(añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtañadnotlibtema, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtañadnotlibtit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtañadnotlibtexto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirnotalibroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirnotalibroLayout.createSequentialGroup()
                        .addComponent(btnañadnotalibro)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirnotalibroLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(157, 157, 157))))
        );
        añadirnotalibroLayout.setVerticalGroup(
            añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirnotalibroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel37)
                .addGap(40, 40, 40)
                .addGroup(añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtañadnotlibtema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtañadnotlibtit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(añadirnotalibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtañadnotlibtexto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnañadnotalibro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel38.setText("Tema:");

        jLabel39.setText("Titulo de referencia:");

        jLabel40.setText("Texto:");

        txtañadnotarttexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañadnotarttextoActionPerformed(evt);
            }
        });

        btnañadnotaarticulo.setText("Añadir");

        jLabel41.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jLabel41.setText("Añadir Nota:");

        javax.swing.GroupLayout añadirnotaarticuloLayout = new javax.swing.GroupLayout(añadirnotaarticulo.getContentPane());
        añadirnotaarticulo.getContentPane().setLayout(añadirnotaarticuloLayout);
        añadirnotaarticuloLayout.setHorizontalGroup(
            añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirnotaarticuloLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel38)
                    .addComponent(jLabel40))
                .addGap(37, 37, 37)
                .addGroup(añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtañadnotarttema, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtañadnotarttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtañadnotarttexto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirnotaarticuloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirnotaarticuloLayout.createSequentialGroup()
                        .addComponent(btnañadnotaarticulo)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirnotaarticuloLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(157, 157, 157))))
        );
        añadirnotaarticuloLayout.setVerticalGroup(
            añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirnotaarticuloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel41)
                .addGap(40, 40, 40)
                .addGroup(añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtañadnotarttema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtañadnotarttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(añadirnotaarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtañadnotarttexto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnañadnotaarticulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel42.setText("Texto:");

        jLabel43.setText("Tema:");

        jLabel44.setText("Titulo:");

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel45.setText("Modificar Nota");

        btnmodifnotlibro.setText("Modificar");

        javax.swing.GroupLayout modificarnota_libroLayout = new javax.swing.GroupLayout(modificarnota_libro.getContentPane());
        modificarnota_libro.getContentPane().setLayout(modificarnota_libroLayout);
        modificarnota_libroLayout.setHorizontalGroup(
            modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarnota_libroLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarnota_libroLayout.createSequentialGroup()
                        .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarnota_libroLayout.createSequentialGroup()
                                .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel42))
                                .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(modificarnota_libroLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtmodifnotlibtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmodifnotlibtema, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(modificarnota_libroLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(txtmodifnotlibtexto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarnota_libroLayout.createSequentialGroup()
                        .addComponent(btnmodifnotlibro)
                        .addContainerGap())))
        );
        modificarnota_libroLayout.setVerticalGroup(
            modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarnota_libroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmodifnotlibtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addGap(40, 40, 40)
                .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmodifnotlibtema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(47, 47, 47)
                .addGroup(modificarnota_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtmodifnotlibtexto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmodifnotlibro)
                .addContainerGap())
        );

        jLabel46.setText("Titulo:");

        jLabel47.setText("Texto:");

        jLabel48.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel48.setText("Modificar Nota:");

        jLabel49.setText("Tema:");

        btnmodifnotarticulo.setText("Modificar");

        javax.swing.GroupLayout modificarnota_articuloLayout = new javax.swing.GroupLayout(modificarnota_articulo.getContentPane());
        modificarnota_articulo.getContentPane().setLayout(modificarnota_articuloLayout);
        modificarnota_articuloLayout.setHorizontalGroup(
            modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarnota_articuloLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarnota_articuloLayout.createSequentialGroup()
                        .addGroup(modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(63, 63, 63)
                        .addGroup(modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmodifnotarttema, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodifnotarttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodifnotarttexto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarnota_articuloLayout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarnota_articuloLayout.createSequentialGroup()
                        .addComponent(btnmodifnotarticulo)
                        .addContainerGap())))
        );
        modificarnota_articuloLayout.setVerticalGroup(
            modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarnota_articuloLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodifnotarttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmodifnotarttema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(modificarnota_articuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodifnotarttexto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnmodifnotarticulo)
                .addGap(13, 13, 13))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablalibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Titulo", "Autor", "Páginas", "Editorial", "Año"
            }
        ));
        scrolllibro.setViewportView(tablalibro);

        añadirlibro.setText("Añadir Libro");
        añadirlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirlibroActionPerformed(evt);
            }
        });

        modiflibro.setText("Modificar Libro");

        notalibro.setText("Añadir Nota");

        lablibbusc.setText("Buscar Libro por:");

        buscarlibro.setText("Buscar");
        buscarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarlibroActionPerformed(evt);
            }
        });

        ComboBoxlibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "titulo", "autor", "paginas", "editorial", "año" }));

        btnelimlibro.setText("Eliminar");

        javax.swing.GroupLayout panelibroLayout = new javax.swing.GroupLayout(panelibro);
        panelibro.setLayout(panelibroLayout);
        panelibroLayout.setHorizontalGroup(
            panelibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolllibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(panelibroLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelibroLayout.createSequentialGroup()
                        .addComponent(añadirlibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modiflibro)
                        .addGap(103, 103, 103)
                        .addComponent(notalibro)
                        .addGap(34, 34, 34))
                    .addGroup(panelibroLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lablibbusc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxlibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(fiellibbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarlibro)
                        .addGap(52, 52, 52))))
            .addGroup(panelibroLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(panelibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnelimlibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtinvisibleelimlibro))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelibroLayout.setVerticalGroup(
            panelibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelibroLayout.createSequentialGroup()
                .addComponent(scrolllibro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(panelibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modiflibro)
                    .addComponent(añadirlibro)
                    .addComponent(notalibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(panelibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lablibbusc)
                    .addComponent(fiellibbusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarlibro)
                    .addComponent(ComboBoxlibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnelimlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtinvisibleelimlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Libros", panelibro);

        tablartic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ISSN", "Autor", "Titulo", "N.Revista", "Año", "Mes", "P.Inicio", "P.Fin"
            }
        ));
        scrollartic.setViewportView(tablartic);

        añadirartic.setText("Añadir Artículo");

        modifartic.setText("Modificar Artículo");

        notaartic.setText("Añadir Nota");

        jLabel1.setText("Buscar Articulo :");

        buscararticulo.setText("Buscar");
        buscararticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscararticuloActionPerformed(evt);
            }
        });

        ComboBoxarticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "autor", "titulo", "N.revista", "año", "mes", "P.inicio", "P.fin" }));

        btnelimarticulo.setText("Eliminar");

        txtinvisibleelimart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvisibleelimartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelarticLayout = new javax.swing.GroupLayout(panelartic);
        panelartic.setLayout(panelarticLayout);
        panelarticLayout.setHorizontalGroup(
            panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollartic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(panelarticLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(añadirartic))
                .addGroup(panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelarticLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(modifartic))
                    .addGroup(panelarticLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(ComboBoxarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(fielartbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notaartic)
                    .addComponent(buscararticulo))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelarticLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnelimarticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtinvisibleelimart))
                .addGap(224, 224, 224))
        );
        panelarticLayout.setVerticalGroup(
            panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelarticLayout.createSequentialGroup()
                .addComponent(scrollartic, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadirartic)
                    .addComponent(modifartic)
                    .addComponent(notaartic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelarticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fielartbusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscararticulo))
                .addGap(33, 33, 33)
                .addComponent(btnelimarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtinvisibleelimart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Articulos", panelartic);

        tablanotaslibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "T.Referencia", "Tema", "Texto"
            }
        ));
        scrollnotas.setViewportView(tablanotaslibro);

        jLabel2.setText("Buscar libros por:");

        jLabel3.setText("Buscar articulos por:");

        txtbuscnottit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscnottitActionPerformed(evt);
            }
        });

        txtbuscnottem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscnottemActionPerformed(evt);
            }
        });

        buscnotatit.setText("Buscar");
        buscnotatit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscnotatitActionPerformed(evt);
            }
        });

        buscnotatem.setText("Buscar");
        buscnotatem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscnotatemActionPerformed(evt);
            }
        });

        tablanotasarticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "T.Referencia", "Tema", "Texto"
            }
        ));
        scrollnotas1.setViewportView(tablanotasarticulo);

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "titulo", "tema" }));

        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "titulo", "tema" }));

        btnmodifnotlib.setText("Modificar Libro");
        btnmodifnotlib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifnotlibActionPerformed(evt);
            }
        });

        btnmodifnotart.setText("Modificar Articulo");

        javax.swing.GroupLayout pabelnotasLayout = new javax.swing.GroupLayout(pabelnotas);
        pabelnotas.setLayout(pabelnotasLayout);
        pabelnotasLayout.setHorizontalGroup(
            pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollnotas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addGroup(pabelnotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollnotas1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pabelnotasLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtbuscnottem, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtbuscnottit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscnotatit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscnotatem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnmodifnotlib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodifnotart, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        pabelnotasLayout.setVerticalGroup(
            pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pabelnotasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(scrollnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbuscnottit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscnotatit)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodifnotlib))
                .addGap(31, 31, 31)
                .addGroup(pabelnotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbuscnottem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscnotatem)
                    .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodifnotart))
                .addGap(58, 58, 58)
                .addComponent(scrollnotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Notas", pabelnotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirlibroActionPerformed

    private void buscarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarlibroActionPerformed
        Libros lib = new Libros();
        lib.Buscar(fiellibbusc.getText(),ComboBoxlibros.getSelectedItem().toString(), tablalibro);
        
        
        
        
    }//GEN-LAST:event_buscarlibroActionPerformed

    private void buscararticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscararticuloActionPerformed
          Articulos art = new Articulos();
        art.Buscar(fielartbusc.getText(),ComboBoxarticulo.getSelectedItem().toString(), tablartic);
    }//GEN-LAST:event_buscararticuloActionPerformed

    private void txtbuscnottitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscnottitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscnottitActionPerformed

    private void txtmodiflibrotituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodiflibrotituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodiflibrotituloActionPerformed

    private void btnmodiflibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodiflibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodiflibroActionPerformed

    private void txtañadlibrotituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañadlibrotituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtañadlibrotituloActionPerformed

    private void txtaañadlibroautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaañadlibroautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaañadlibroautorActionPerformed

    private void txtañadartautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañadartautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtañadartautorActionPerformed

    private void txtañadartnomrevistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañadartnomrevistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtañadartnomrevistActionPerformed

    private void txtañadartmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañadartmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtañadartmesActionPerformed

    private void txtmodifartpaginicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodifartpaginicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodifartpaginicActionPerformed

    private void txtmodifartautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodifartautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodifartautorActionPerformed

    private void txtmodifartañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodifartañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodifartañoActionPerformed

    private void buscnotatitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscnotatitActionPerformed
       
        Notas_libro notalib = new Notas_libro();
        notalib.Buscar(txtbuscnottit.getText(),ComboBox1.getSelectedItem().toString(), tablanotaslibro);
       // modelo_Libros.Buscar(espacio_buscar_libros.getText(),combobox_libros.getSelectedItem().toString(),tabla_libros);
        
    }//GEN-LAST:event_buscnotatitActionPerformed

    private void txtbuscnottemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscnottemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscnottemActionPerformed

    private void txtañadnotlibtemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañadnotlibtemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtañadnotlibtemaActionPerformed

    private void txtañadnotarttextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañadnotarttextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtañadnotarttextoActionPerformed

    private void buscnotatemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscnotatemActionPerformed
         Notas_articulo notasart= new Notas_articulo();
        notasart.Buscar(txtbuscnottem.getText(),ComboBox2.getSelectedItem().toString(),tablanotasarticulo);
    }//GEN-LAST:event_buscnotatemActionPerformed

    private void txtinvisibleelimartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvisibleelimartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvisibleelimartActionPerformed

    private void btnmodifnotlibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifnotlibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodifnotlibActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBox1;
    public javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JComboBox<String> ComboBoxarticulo;
    private javax.swing.JComboBox<String> ComboBoxlibros;
    public javax.swing.JDialog añadir_articulo;
    public javax.swing.JDialog añadir_libro;
    public javax.swing.JButton añadirartic;
    public javax.swing.JButton añadirlibro;
    public javax.swing.JDialog añadirnotaarticulo;
    public javax.swing.JDialog añadirnotalibro;
    public javax.swing.JButton btnañadirarticulo;
    public javax.swing.JButton btnañadirlibro;
    public javax.swing.JButton btnañadnotaarticulo;
    public javax.swing.JButton btnañadnotalibro;
    public javax.swing.JButton btnelimarticulo;
    public javax.swing.JButton btnelimlibro;
    public javax.swing.JButton btnmodifarticulo;
    public javax.swing.JButton btnmodiflibro;
    public javax.swing.JButton btnmodifnotart;
    public javax.swing.JButton btnmodifnotarticulo;
    public javax.swing.JButton btnmodifnotlib;
    public javax.swing.JButton btnmodifnotlibro;
    public javax.swing.JButton buscararticulo;
    public javax.swing.JButton buscarlibro;
    public javax.swing.JButton buscnotatem;
    public javax.swing.JButton buscnotatit;
    public javax.swing.JTextField fielartbusc;
    private javax.swing.JTextField fiellibbusc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lablibbusc;
    public javax.swing.JButton modifartic;
    public javax.swing.JDialog modificar_articulo;
    public javax.swing.JDialog modificar_libro;
    public javax.swing.JDialog modificarnota_articulo;
    public javax.swing.JDialog modificarnota_libro;
    public javax.swing.JButton modiflibro;
    public javax.swing.JButton notaartic;
    public javax.swing.JButton notalibro;
    private javax.swing.JPanel pabelnotas;
    private javax.swing.JPanel panelartic;
    private javax.swing.JPanel panelibro;
    private javax.swing.JScrollPane scrollartic;
    private javax.swing.JScrollPane scrolllibro;
    private javax.swing.JScrollPane scrollnotas;
    private javax.swing.JScrollPane scrollnotas1;
    public javax.swing.JTable tablalibro;
    public javax.swing.JTable tablanotasarticulo;
    public javax.swing.JTable tablanotaslibro;
    public javax.swing.JTable tablartic;
    public javax.swing.JTextField txtaañadlibroautor;
    public javax.swing.JTextField txtañadartautor;
    public javax.swing.JTextField txtañadartaño;
    public javax.swing.JTextField txtañadartmes;
    public javax.swing.JTextField txtañadartnomrevist;
    public javax.swing.JTextField txtañadartpagfin;
    public javax.swing.JTextField txtañadartpaginic;
    public javax.swing.JTextField txtañadarttitulo;
    public javax.swing.JTextField txtañadlibroaño;
    public javax.swing.JTextField txtañadlibroedit;
    public javax.swing.JTextField txtañadlibronpag;
    public javax.swing.JTextField txtañadlibrotitulo;
    public javax.swing.JTextField txtañadnotarttema;
    public javax.swing.JTextField txtañadnotarttexto;
    public javax.swing.JTextField txtañadnotarttitulo;
    public javax.swing.JTextField txtañadnotlibtema;
    public javax.swing.JTextField txtañadnotlibtexto;
    public javax.swing.JTextField txtañadnotlibtit;
    private javax.swing.JTextField txtbuscnottem;
    private javax.swing.JTextField txtbuscnottit;
    public javax.swing.JTextField txtinvisibleelimart;
    public javax.swing.JTextField txtinvisibleelimlibro;
    public javax.swing.JTextField txtmodifartautor;
    public javax.swing.JTextField txtmodifartaño;
    public javax.swing.JTextField txtmodifartmes;
    public javax.swing.JTextField txtmodifartnomrevist;
    public javax.swing.JTextField txtmodifartpagfin;
    public javax.swing.JTextField txtmodifartpaginic;
    public javax.swing.JTextField txtmodifarttitulo;
    public javax.swing.JTextField txtmodiflibroautor;
    public javax.swing.JTextField txtmodiflibroaño;
    public javax.swing.JTextField txtmodiflibroedit;
    public javax.swing.JTextField txtmodiflibronpag;
    public javax.swing.JTextField txtmodiflibrotitulo;
    public javax.swing.JTextField txtmodifnotarttema;
    public javax.swing.JTextField txtmodifnotarttexto;
    public javax.swing.JTextField txtmodifnotarttitulo;
    public javax.swing.JTextField txtmodifnotlibtema;
    public javax.swing.JTextField txtmodifnotlibtexto;
    public javax.swing.JTextField txtmodifnotlibtitulo;
    // End of variables declaration//GEN-END:variables

   
}
